const topics = [
  "Pineapple belongs on pizza",
  "Hot dogs are sandwiches",
  "Cats are better than dogs",
  "Cereal is soup",
  "The toilet paper roll should go over, not under",
  "Water is wet",
  "A taco is a sandwich",
  "Pluto is a planet",
  "GIF is pronounced with a hard G",
  "The book is always better than the movie",
  "Breakfast for dinner is superior to dinner for dinner",
  "Socks with sandals are acceptable",
  "The chicken came before the egg",
  "Ketchup belongs on eggs",
  "Winter is better than summer",
  "Android is better than iPhone",
  "PC is better than console",
  "Invisibility is a better superpower than flying",
  "It's okay to recline your seat on an airplane",
  "Milk goes in before the cereal",
  "A hot dog is a taco",
  "Die Hard is a Christmas movie",
  "Chocolate is better than vanilla",
  "Texting is better than calling",
  "Morning showers are better than night showers",
  "Pizza is better cold",
  "Aliens definitely exist",
  "Time travel would be a bad idea",
  "Living in the city is better than the countryside",
  "Pop music is the best genre",
  "School uniforms should be mandatory",
  "Robots will take over most jobs",
  "Social media does more harm than good",
  "Math is the most important subject",
  "Homework should be banned",
  "Video games are a sport",
  "You should always tip at restaurants",
  "Naps should be mandatory at work",
  "Birds are the best pets",
  "The Oxford comma is essential",
  "Pancakes are better than waffles",
  "Friday is the best day of the week",
  "Tea is better than coffee",
  "The speed limit should be higher",
  "Rainbows are overrated",
  "Monkeys would make good coworkers",
  "Soup is a drink, not a food",
  "You should shower before bed, not in the morning",
  "Sleeping with socks on is fine",
  "White chocolate is real chocolate",
]

export function getRandomTopic() {
  return topics[Math.floor(Math.random() * topics.length)]
}
